POST http://localhost:3000/api/solve
Content-Type: application/json; charset=utf-8

{
    "puzzle": "..9..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6.."
}
################################
POST http://localhost:3000/api/solve
Content-Type: application/json; charset=utf-8

{
    "notpuzzle": "..9..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6.."
}
################################
POST http://localhost:3000/api/solve
Content-Type: application/json; charset=utf-8

{
    "puzzle": "AA9..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6.."
}
################################
POST http://localhost:3000/api/solve
Content-Type: application/json; charset=utf-8

{
    "puzzle": "9..5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6.."
}
################################
POST http://localhost:3000/api/solve
Content-Type: application/json; charset=utf-8

{
    "puzzle": "9....5.1.85.4....2432......1...69.83.9.....6.62.71...9......1945....4.37.4.3..6.."
}
################################
