POST http://localhost:3000/api/issues/fcc-project
Content-Type: application/json; charset=utf-8

{
    "issue_title": "Faux Issue Title",
    "issue_text": "Functional Test - Required Fields Only",
    "created_by": "fCC"
}
################################
POST http://localhost:3000/api/issues/fcc-project
Content-Type: application/json; charset=utf-8

{
    "project_title": "testproject",
    "issue_title": "Test POST successful?",
    "issue_text": "Is it going to pass though or fail?",
    "created_by": "TestGuy",
    "assigned_to": "SolverGuy",
    "open": true,
    "status_text": "Under QA check",
}
################################
POST http://localhost:3000/api/issues/fcc-project
Content-Type: application/json; charset=utf-8

{
    "project_title": "testproject",
    "issue_title": "Test POST ok?",
    "issue_text": "Is it going to suck big time?",
    "created_by": "TestDude"
}
################################